import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tax it",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: "../../public/fonts/Poppins-SemiBold.ttf",
  display: "swap",
});

const lightFont = localFont({
  src: "../../public/fonts/Poppins-Light.ttf",
  display: "swap",
});

const mediumFont = localFont({
  src: "../../public/fonts/Poppins-Medium.ttf",
  display: "swap",
});

const boldFont = localFont({
  src: "../../public/fonts/Poppins-Bold.ttf",
  display: "swap",
});

const regularFont = localFont({
  src: "../../public/fonts/Poppins-Regular.ttf",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          myFont.className,
          lightFont.className,
          mediumFont.className,
          boldFont.className,
          regularFont.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
